### ISSUE TITLE
Can I change in VueJs double braces  template

### ISSUE THREAD

**Issue by UMUTBAYGUT** [erdaltsksn/ama#1]
Hello Erdal , 

As you know , in Vuejs we can use double braces "{{ }}" if we want to render any variable. 

I just wonder that can we change the double braces to another thing , example {# #}.

Thanks

**Comment by erdaltsksn** [comment]
```
new Vue({
  delimiters: ['{#', '#}']
})
```

or

```
app.config.compilerOptions.delimiters = ['{#', '#}']    
```

Sources:
https://vuejs.org/v2/api/#delimiters
https://v3.vuejs.org/api/application-config.html#compileroptions-delimiters
